kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-propagator-global
subjects:
- kind: ServiceAccount
  name: governance-policy-propagator
  namespace: governance
# - kind: User
#   apiGroup: rbac.authorization.k8s.io
#   name: 'hcm:clusters:calamari:calamari'
roleRef:
  kind: ClusterRole
  name: governance-policy-propagator
  apiGroup: rbac.authorization.k8s.io
